#OPENAI_API_KEY = "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"

OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4"
OPENAI_TEMPERATURE = 0

# NEO4J_URI="bolt://3.236.204.82:7687"
# NEO4J_USERNAME="neo4j"
# NEO4J_PASSWORD="colleges-silicon-factors"
# NEO4J_DATABASE="neo4j"

# NEO4J_URI="bolt://3.83.29.122:7687"
# NEO4J_USERNAME="neo4j"
# NEO4J_PASSWORD="mitten-lard-apportionments"
# NEO4J_DATABASE="neo4j"

NEO4J_URI="neo4j+s://34e16a7e.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="zkWdwq5DkYvhBk2REwXwxOE9eXnzV87wIk4OZqdAa30"
NEO4J_DATABASE="neo4j"